### ISSUE TITLE
Error while trying to run the cli

### ISSUE THREAD

**Issue by mefarazath** [IsurangaPerera/cli#2]
Tried running the tool following the instructions given in the README.md

```
  farazath  ~/Desktop/cli   master   cli config -url localhost:9443 -u admin -p password 
The assembly mscorlib.dll was not found or could not be loaded.
It should have been installed in the `/usr/lib/mono/2.0/mscorlib.dll' directory.
```
looks like additional libs are required... would be great if you could have some info to build from source.

**Comment by IsurangaPerera** [comment]
Try running (within the project directory)
`go build .`
`./cli config -u username -p password -url base_url -s1 [endpoint]`

**Comment by mefarazath** [comment]
Looks like you need import a remote package first.

`go get github.com/IsurangaPerera/mow.cli`

and then do the `go build .`

**Comment by IsurangaPerera** [comment]
README updated to reflect changes
