### ISSUE TITLE
'cli config' command doesn't work as expected

### ISSUE THREAD

**Issue by mefarazath** [IsurangaPerera/cli#3]
As I understood the `cli config` command initializes the credentials necessary to do the service calls to SOAP endpoints?

I tried executed the command and got the below output

![image](https://cloud.githubusercontent.com/assets/5237653/24203904/f31bf68e-0f3c-11e7-8f66-ed1e543e0c82.png)

Can you explain what is the expected output?

**Comment by IsurangaPerera** [comment]
This is an issue due to new command line parser.
