### ISSUE TITLE
ListAllUsers command returns empty data

### ISSUE THREAD

**Issue by mefarazath** [IsurangaPerera/cli#4]
I went ahead and excuted ./cli listAllUsers
Here's the output I got. Can you explain the output?

![image](https://cloud.githubusercontent.com/assets/5237653/24204028/405e0cd4-0f3d-11e7-8ef4-2404fde0ea4d.png)

**Comment by IsurangaPerera** [comment]
I've modified the code. Now it return all the users registered with the IS
