### ISSUE TITLE
ListAllUsers prints an additional empty user

### ISSUE THREAD

**Issue by mefarazath** [IsurangaPerera/cli#6]
**ListAllUsers** operation works fine. But I noticed that it prints out an additional empty user when listing.
Checkout the screenshot below. I have two created two users in my Identity Server but the commands prints out three uses, last one being an empty one.

![image](https://cloud.githubusercontent.com/assets/5237653/24323260/2e543b90-1199-11e7-8904-9c3d3b3acdfc.png)

**Comment by IsurangaPerera** [comment]
I updated the listAllUsers to list down just users. please update your local repo

**Comment by mefarazath** [comment]
Now it only prints one user. Bug?

**Comment by IsurangaPerera** [comment]
I'll check on that.Maybe a problem with list traversal

**Comment by IsurangaPerera** [comment]
Works fine for me
![image](https://cloud.githubusercontent.com/assets/12288369/24323640/a5d59c72-119e-11e7-84a9-633421e5b9d8.png)

Above is  a screenshot of output from web interface and CLI tool

**Comment by mefarazath** [comment]
Let me check once again :smile:

**Comment by mefarazath** [comment]
Yeah works fine :+1:
