### ISSUE TITLE
Improve config command

### ISSUE THREAD

**Issue by mefarazath** [IsurangaPerera/cli#7]
Currently in the config command we set the following,

1. Username and Password to do the service calls
2. Base URL
3. Service Endpoints

IMO, we can get rid of configuring service endpoints since we already know them and they are not going to change. For example: UserAdmin endpoint will always be services/UserAdmin.UserAdminHttpsSoap11Endpoint or services/UserAdmin.UserAdminHttpsSoap12Endpoint/ and only the baseURL might change.

Even the baseURL we can have a default value of localhost:9443 and override the value if someone sets it using the config command.

Also noticed that config command gives an error although it was successful...

![image](https://cloud.githubusercontent.com/assets/5237653/24323333/1f4f7bea-119a-11e7-8f18-d383e9dffbcc.png)

**Comment by IsurangaPerera** [comment]
I have already set default endpoint values
using [1] is enough

[1] `cli config -u [user name] -p [password] -u [base url]
`
I'll update the README with default values for each command parameter
